name: Deploy to Azure VM


on:

  push:

    branches: [ master]


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Deploy via SSH

      uses: appleboy/ssh-action@v0.1.6

      with:

        host: ${{ secrets.VM_IP }}

        username: ${{ secrets.VM_USER }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |

          cd node-app

          git pull origin master

          npm install

          pm2 restart my-app
